[package]
name = 'openvr-driver-sys'
version = '1.10.30-update.0'
authors = ['Riccardo Zaglia <github.com/Riccardo Zaglia>']
license = 'MIT'
edition = '2018'

[lib]
crate-type = ['rlib']

[build-dependencies]
bindgen = '0.53'
cc = '1.0'
regex = '1.3'